service: serverless-lambda-template # NOTE: update this with your service name

frameworkVersion: "4"

variablesResolutionMode: 20210326

custom:
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'develop'
    stg:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'staging'
    prod:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'production'

plugins:
  - serverless-plugin-tracing
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment: ${self:custom.settings.${self:custom.stage}}
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  hello:
    handler: src/index.hello
    tracing: true
    events:
      - http:
          method: get
          path: v1/hello