service: serverless-lambda-template # NOTE: update this with your service name

frameworkVersion: "4"

variablesResolutionMode: 20210326
build:
  esbuild: false
custom:
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'develop'
    stg:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'staging'
    prod:
      STAGE: ${self:custom.stage}
      NODE_ENV: 'production'
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  apigwBinary:
    types:
      - "*/*"
  prune:
    automatic: true
    includeLayers: true
    number: 5

plugins:
  - serverless-plugin-tracing
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment: ${self:custom.settings.${self:custom.stage}}
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  hello:
    handler: src/index.hello
    tracing: true
    events:
      - http:
          method: get
          path: v1/hello